title: G-DANTs PAGE
theme: jekyll-theme-minimal
show_downloads: "false"
description: <b>The adventures of a geek programmer who believes that artificial intelligence can be trained to prepare his own coffee</b><ul><li>Projects <strong>Check out!</strong></li><li>About Me <strong>Check out!</strong></li><hr>
