title: G-DANTs PAGE
theme: jekyll-theme-minimal
logo: logo.jpeg
show_downloads: "false"
relative_url: "/index.md"
description: 
      <p>The adventures of a geek programmer 
      who believes that artificial intelligence can be trained to prepare his own coffee</p>
      <ul>
      
      <li>
      <center>Projects 
      <strong>
      <a href="/projects.md">LINK</a>
      </strong></center>
      </li>
      
      <li><center>About Me 
      <strong>
      <a href="/about.md">LINK</a>
      </strong>
      </center>
      </li>
      
      <li><center>Blog Posts <strong>SOON</strong></center></li>
      </ul>
