title: G-DANTs PAGE
theme: jekyll-theme-minimal
show_downloads: "false"
description: <p>The adventures of a geek programmer who believes that artificial intelligence can be trained to prepare his own coffee</p><ul><li class="marker">Projects <strong>LINK</strong></li><li class="marker">About Me <strong>LINK</strong></li><hr>
